version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: gatsby-plugin-image
    versions:
    - 0.7.2
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.12.0
