export const projectsPage = [
  {
    header_main: "AuraTattoo",
    paragraph: "",
    table: {
      type: "Commercial",
      stack: ["React", "Styled-components", "Netlify"],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/Ethereal",
      },
      live: {
        text: "Live view",
        link: "https://www.aurareykjavik.com/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "NTS-Radio Scrapper",
    paragraph: "",
    table: {
      type: "Hackathon",
      stack: [
        "NodeJS",
        "Express",
        "React",
        "Styled-components",
        "Puppeteer",
        "Netlify",
        "Heroku",
      ],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/WebScrapper_Client",
      },
      live: {
        text: "Live view",
        link: "https://nts-scrapper.netlify.app/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "Novid",
    paragraph: "",
    table: {
      type: "Team Project",
      stack: [
        "NodeJS",
        "Express",
        "MongoDB",
        "Mongoose",
        "React",
        "Netlify",
        "Heroku",
      ],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/CovidTracker_Client",
      },
      live: {
        text: "Live view",
        link: "https://novid-client.netlify.app/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "CareerToGo",
    paragraph: "",
    table: {
      type: "Internship/Commercial",
      stack: ["VueJS", "NuxtJS", "TailwindCSS", "MySQL", "AWS"],
      code: {
        text: "Ask for access",
        link: "mailto:ryjewski@gmail.com",
      },
      live: {
        text: "Official website",
        link: "https://www.careertogo.dk/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "ToDo",
    paragraph: "",
    table: {
      type: "Personal",
      stack: ["NodeJS", "Express", "MongoDB", "Mongoose", "GraphQL"],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/ToDo_Server",
      },
      live: {
        text: "Live view",
        link: "https://github.com/Ryjekk/ToDo_Server",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "Algerio",
    paragraph: "",
    table: {
      type: "Personal",
      stack: ["React", "Netlify", "CSS Modules"],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/Sort_Visualizer",
      },
      live: {
        text: "Live view",
        link: "https://sort-algo.netlify.app/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
  {
    header: "VueJS Portfolio",
    paragraph: "",
    table: {
      type: "Personal",
      stack: ["VueJS", "SASS", "Netlify"],
      code: {
        text: "Repository",
        link: "https://github.com/Ryjekk/NewPortfolio",
      },
      live: {
        text: "Live view",
        link: "https://ryjewsky.netlify.app/",
      },
    },
    img_project_one: "",
    header_goal: "",
    paragraph_goal_one: "",
    paragraph_goal_two: "",
    header_explanation: "",
    paragraph_explanation_one: "",
    paragraph_explanation_two: "",
    img_badges: "",
    img_project_overall: "",
    header_problems: "",
    paragraph_problems: "",
    img_project_two: "",
    header_lesson: "",
  },
];
